title:             Voll The Blog
email:             vollthegreat@example.com
description:       Dev dev dev
author:            Voll The Great
baseurl:           "/startbootstrap-clean-blog-jekyll"
url:               "http://vollthegreat.github.io"

# Social Profiles
twitter_username:  nenitel
github_username:   vollthegreat
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
